name: V8 Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      # Checkout repos and submodules
      - uses: actions/checkout@v2
      - name: Setup Environments
        run: ./.github/scripts/ci-setup.sh

      # Be aware that any changes made to the following steps should be made to ci-test.sh as well.
      # MMTk core tests the V8 binding by invoking ci-test.sh.

      - name: Build MMTk NoGC
        run: ./.github/scripts/build-mmtk.sh

      - name: Style check Rust
        run: ./.github/scripts/ci-style.sh

      - name: Get V8 Sources
        run: ./.github/scripts/get-v8.sh

      - name: Build V8 with MMTk
        run: ./.github/scripts/build-v8.sh

      - name: Run V8 Tests
        run: ./.github/scripts/test-v8.sh

  msrv:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-msrv
        run: cargo install cargo-msrv
      # Verify the MSRV defined in Cargo.toml
      - name: Verify MSRV
        run: cargo msrv --path mmtk verify
      # If the previous step fails, find MSRV
      - name: Find MSRV
        if: failure()
        run: cargo msrv --path mmtk
